### ISSUE TITLE
detection.py file

### ISSUE THREAD

**Issue by LucasAssis00** [PSUCyberSecurityLab/AIforCybersecurity#7]
I've got the CFG, sequences and images or the database, then after running the neural networks files I tried to run the detection cell, but it indicated:
[Errno 2] No such file or directory: 'data/CFG_split_data.pickle'
However, I could not find where this specific folder is generated, is it necessary to create the folder and then add all the files in it?

**Comment by LucasAssis00** [comment]
Also, the tensorflow issues that came are like:
"I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags."
"W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT"
Those occur even after installing 
"pip install tensorrt" or "!python3 -m pip install --upgrade tensorrt"

**Comment by Moirai7** [comment]
Did you run tf_utils.py? split() will generate the training and test dataset.

**Comment by Moirai7** [comment]
If you do not have GPU, install tensorflow. https://www.tensorflow.org/install
Also you may need this. https://stackoverflow.com/questions/64450037/tensorflow-binary-is-optimized-to-use-the-following-cpu-instructions-in-performa

**Comment by LucasAssis00** [comment]
> If you do not have GPU, install tensorflow. https://www.tensorflow.org/install Also you may need this. https://stackoverflow.com/questions/64450037/tensorflow-binary-is-optimized-to-use-the-following-cpu-instructions-in-performa

Is this done in the same way in google colab? I am trying to execute here but it's not working.

**Comment by Moirai7** [comment]
It should work with colab

**Comment by LucasAssis00** [comment]
The warnings are coming like this:
"
I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/detection.py", line 184, in <module>
    train('cnn')
  File "/content/detection.py", line 109, in train
    train_ds, val_ds = prepare_data_image()
  File "/content/detection.py", line 20, in prepare_data_image
    check_distribution(train_set, alls)
  File "/content/tf_utils.py", line 34, in check_distribution
    lbs.append(config.malware_label  if ns[f].find('Virus') != -1 else config.benign_label)
IndexError: list index out of range
"

Could this list be reffering to the files in CFG/Seq-ori/images folders? I cannot find a way to see what is being done in detection.py, as the variable folder does not show anything.

**Comment by Moirai7** [comment]
https://github.com/PSUCyberSecurityLab/AIforCybersecurity/blob/18cd041b654a1abf47e003680d2e59d3408eba7c/Chapter6-Malware-Classification/detection.py#LL20C5-L20C40
'alls' refers to the path of the data.
'train_set' refers to the splited training dataset.
you need make sure their sizes are consistent.

**Comment by LucasAssis00** [comment]
No variables are shown as I run the .py files by themselves, with "!python something.py", so I cannot see where it starts going wrong

**Comment by Moirai7** [comment]
You could print(len(alls), len(train_set)) to find the sizes.
